### ISSUE TITLE
undefined is not a constructor

### ISSUE THREAD

**Issue by spamguy** [bendrucker/sinon-as-promised#34]
I'm trying to create a mocked service that returns promises as generated through sinon-as-promised. I receive this error when I run my test:
```
	undefined is not a constructor (evaluating 'sinon.stub().resolves(variant)')
		at /var/folders/hv/4tc81kzx3z94xsb5l9kxg2mc3cl9j0/T/7f9ddd80a441f1bbbd5bc39d74cd6e76.browserify:1398:46
		at invoke (/bower_components/angular/angular.js:4473:22)
		at workFn (/bower_components/angular-mocks/angular-mocks.js:2426:26)
```
I did my best to adapt your Angular example. This is what I have:
```
describe('MyController', function() {
    'use strict';

    var $rootScope,
        $scope,
        mockService,
        $state,
        $injector,
        sinonAsPromised = require('sinon-as-promised'),
        $q,
        variant = { name: 'something' },
        sandbox;

    beforeEach(inject(function(_$q_, _$rootScope_, _$state_, _$injector_) {
        $rootScope = _$rootScope_;
        $state = _$state_;
        $injector = _$injector_;
        sandbox = sinon.sandbox.create();
        $q = _$q_;
        sinonAsPromised($q);
    }));

    afterEach(function() {
        sandbox.restore();
    });

    beforeEach(inject(function($controller) {
        $scope = $rootScope.$new();
        mockService = {
            getVariant: sandbox.stub().resolves(variant)
        };
    }));

    beforeEach(inject(function($rootScope, $controller, $q) {
        $scope = $rootScope.$new();
        $controller('UserGamesController', { $scope: $scope, gameService: mockService });
    }));

    it('resolves data', function() {
        $rootScope.$digest();
        // No expect(): exception thrown in beforeEach()
    });
});
```

**Comment by fearphage** [comment]
`sinonAsPromised` expects you to pass a new `Promise` constructor (`Q.Promise` for instance) into when you call it as a function. See [usage section](/bendrucker/sinon-as-promised/blob/d2b2dd0966fa9b2e0cacabfe4ab18c93c52ab3a6/README.md#usage) in the readme.

**Comment by bendrucker** [comment]
Hard to say, that error isn't coming from sinon-as-promised. Can look further with a full project since I need to know versions et al to actually diagnose anything.
